.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. fujicoin_qt test_fujicoin_qt
clean: FORCE
	$(MAKE) -C .. fujicoin_qt_clean test_fujicoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_fujicoin_qt_check
fujicoin-qt fujicoin-qt.exe: FORCE
	 $(MAKE) -C .. fujicoin_qt
