#ifndef FUJICOIN_CHAINPARAMSSEEDS_H
#define FUJICOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the fujicoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x36,0x45,0x6c,0x47}, 3777} //54.69.108.71
};

static SeedSpec6 pnSeed6_test[] = {
    
};
#endif // FUJICOIN_CHAINPARAMSSEEDS_H
